version: '3'
services:
  caddy:
    image: abiosoft/caddy
    restart: always
    environment:
      - ACME_AGREE=true
    volumes:
      - "$service_dir/conf/caddy/Caddyfile:/etc/Caddyfile:ro"
      - "$data_dir/caddy-logs:/logs:rw"
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true
  ssmgr:
    image: geektr/ssmgr
    restart: always
    env_file:
      - "$secrets_dir/secrets.env"
    volumes:
      - "$service_dir/conf/ssmgr/config.js:/usr/local/share/.config/yarn/global/node_modules/shadowsocks-manager/services/config.js"
      - "$service_dir/conf/ssmgr/skin/fs_laughingman.html:/usr/local/share/.config/yarn/global/node_modules/shadowsocks-manager/plugins/webgui/public/views/skin/fs_laughingman.html"
      - "$service_dir/conf/ssmgr/favicon.png:/favicon.png"
  mysql:
    image: mysql:5
    restart: always
    env_file: 
      - "$secrets_dir/secrets.env"
    command: --sql_mode=""
    volumes:
      - "mysql-data:/var/lib/mysql"
    restart: always

volumes: 
  mysql-data:
